stages:
  prepare:
    cmd: python ./mdsist/preprocessing.py ./data/raw/train-00000-of-00001.parquet
      ./data/raw/test-00000-of-00001.parquet ./data/processed/train.parquet ./data/processed/validation.parquet
      ./data/processed/test.parquet
    deps:
    - ./data/raw/test-00000-of-00001.parquet
    - ./data/raw/train-00000-of-00001.parquet
    - ./mdsist/preprocessing.py
    params:
    - preprocessing.random_state
    - preprocessing.training_split
    - preprocessing.validation_split
    outs:
    - ./data/processed/test.parquet
    - ./data/processed/train.parquet
    - ./data/processed/validation.parquet


  train:
    cmd: python mdsist/modeling/train.py data/processed/train.parquet data/processed/validation.parquet
      models/model.pt
    deps:
    - mdsist/architectures.py
    - data/processed
    - mdsist/dataset.py
    - mdsist/modeling/train.py
    - mdsist/trainer.py
    - mdsist/util.py
    params:
    - training.batch_size
    - training.epochs
    - training.learning_rate
    - training.seed
    - training.experiment_id

  test:
    cmd: python mdsist/modeling/test.py data/processed/test.parquet
    deps:
    - data/processed/test.parquet
    - mdsist/dataset.py
    - mdsist/trainer.py
    - mdsist/util.py
    - mdsist/modeling/test.py
    params:
    - testing.batch_size
    - testing.experiment_id
