name: MDSIST Tests
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    env: 
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DVC_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DVC_PASSWORD }}

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with: 
          python-version: 3.9

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --no-cache

      - name: MLFlow credentials
        run: |
          poetry run dvc remote modify origin --local auth basic
          poetry run dvc remote modify origin --local user ${{ secrets.DVC_USERNAME }}
          poetry run dvc remote modify origin --local password ${{ secrets.DVC_PASSWORD }}
          poetry run dvc pull

      - name: Run tests
        run: |
          poetry run coverage run -m pytest

      - name: Pre-commit
        run: |
          poetry run pre-commit run --all-files


  cd: 
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build
        run: docker build -t mdsist .
      - name: Tags
        run: |
          docker tag mdsist ${{ secrets.DOCKER_USER }}/mdsist:${{ github.sha }}
          docker tag mdsist ${{ secrets.DOCKER_USER }}/mdsist:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/mdsist:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/mdsist:latest

