name: MDSIST Tests
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with: 
          python-version: 3.9

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --no-cache

      - name: MLFlow credentials
        run: |
          poetry run dvc remote modify origin --local auth basic
          poetry run dvc remote modify origin --local user ${{ secrets.DVC_USERNAME }}
          poetry run dvc remote modify origin --local password ${{ secrets.DVC_PASSWORD }}

      - name: Run tests
        run: |
          poetry run coverage run -m pytest
    
  discord-notification:
    needs: ci
    if: ${{ failure() && github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        id: discord
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"content": "MDSIST Test failed. View details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
